language: node_js

cache:
  yarn: true

script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh_token
  local_dir: dist
  env:
    - VUE_APP_BACKEND_URL=https://scrum-poker-backend.herokuapp.com
  on:
    branch: master
